project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "resources/*.qmd"

website:
  title: "Aaron Erlich"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Lab"
        href: lab.qmd
      - text: "C.V."
        href: cv.qmd
      - text: "Letter of Rec"
        href: resources/letters.qmd
      # - text: "Research"
      #   href: research.qmd
      # - text: "Resources"
      #   menu:
      #     - text: "Georgia Bibliography"
      #       href: resources/georgia-bib.qmd
      #     - text: "Undergraduate Thesis and Internships"
      #       href: resources/thesis-internships.qmd
      #     - text: "Political Science Writing"
      #       href: resources/writing.qmd
      # - text: "Teaching"
      #   menu:
      #     - text: "Teaching"
      #       href: teaching.qmd
      #     - text: "R Tutorials"
      #       href: r-tutorials.qmd

format:
  html:
    theme: cosmo
    css:
      - styles.css
      - https://cdn.jsdelivr.net/npm/academicons@1.9.2/css/academicons.min.css
    toc: false
    include-after-body: _generated/i18n-toggle.html
