#!/usr/bin/env python3
"""build-cv-pdf.py — compile the Overleaf LaTeX CV locally and install the PDF
into files/Erlich_CV_en.pdf, which the CV page's Download button points at.

Why this exists
---------------
The web CV and the LaTeX CV are both generated from Zotero + cv.yml, but the
PDF was only ever produced by Overleaf's auto-compile and copied in by hand —
which never happened, so files/Erlich_CV_en.pdf did not exist and the Download
button 404'd. This closes that loop without leaving the machine.

Inputs
------
  main.tex             the hand-maintained CV body (Overleaf, English only)
  res.cls              Michael DeCorte's resume class; NOT in TeX Live, so it
                       has to come from the project rather than the TeX tree
  cv_publications.tex  generated by build-cv-latex.py — always taken from
                       _generated/, never from Dropbox, so the PDF matches the
                       web CV built in the same run

main.tex and res.cls live in the Dropbox-synced Overleaf folder. Dropbox keeps
them as ONLINE-ONLY placeholders by default (0 bytes on disk, xattr
com.dropbox.placeholder), so this script falls back to the repo-local cache in
_data/ and tells you which file needs materializing.

Usage
-----
  python3 scripts/build-cv-latex.py && python3 scripts/build-cv-pdf.py
  python3 scripts/build-cv-pdf.py --keep    # leave the build dir for debugging
"""
from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OVERLEAF = Path.home() / "Dropbox" / "Apps" / "Overleaf" / "Erlich_CV_Version_Control"
GENERATED = REPO / "_generated" / "cv_publications.tex"
# Second generated input: \cvlastupdated and \cvservicelists, built from
# _data/cv.yml by build-cv-latex.py. Taken from _generated/ like the other one,
# so the PDF and the web CV are always built from the same data in one run.
GENERATED_META = REPO / "_generated" / "cv_generated.tex"
CACHE = REPO / "_data"                      # fallback copies of main.tex / res.cls
OUT = REPO / "files" / "Erlich_CV_en.pdf"

# (name in the build dir, Dropbox source, repo-local fallback or None)
#
# main.tex has NO fallback on purpose. _data/cv_source.tex looks like a spare
# copy but is a dated reference snapshot used as parser input — it still has
# the publication lists inline and does not compile. Building from it would
# silently produce a months-old CV, which is worse than failing. The Dropbox
# copy is the only acceptable source.
#
# res.cls does have a cache: it is not in TeX Live (Overleaf supplies it) and
# the file has not changed since 2001, so a repo copy is safe and permanent.
SOURCES = [
    ("main.tex", OVERLEAF / "main.tex", None),
    ("res.cls",  OVERLEAF / "res.cls",  CACHE / "res.cls"),
]


def placeholder(p: Path) -> bool:
    """True if Dropbox is holding this file online-only (0 bytes on disk)."""
    try:
        return p.exists() and p.stat().st_size == 0
    except OSError:
        return False


def resolve(name: str, dropbox: Path, cache: Path | None) -> Path | None:
    if dropbox.is_file() and not placeholder(dropbox):
        print(f"  {name:20s} <- Overleaf/Dropbox")
        return dropbox
    if placeholder(dropbox):
        print(f"  {name:20s} !  Dropbox holds this online-only (0 bytes on disk).")
        print(f"  {'':20s}    Finder -> right-click the file in")
        print(f"  {'':20s}    {OVERLEAF}")
        print(f"  {'':20s}    -> Make Available Offline. One time; then this")
        print(f"  {'':20s}    script stays current automatically.")
    if cache is not None and cache.is_file() and cache.stat().st_size:
        print(f"  {name:20s} <- repo cache {cache.relative_to(REPO)}")
        return cache
    return None


def main() -> int:
    keep = "--keep" in sys.argv

    if not shutil.which("xelatex"):
        sys.exit("xelatex not found. TinyTeX/MacTeX must be on PATH.")
    for g in (GENERATED, GENERATED_META):
        if not g.is_file():
            sys.exit(f"{g} missing — run scripts/build-cv-latex.py first.")

    print("Resolving inputs:")
    resolved = {name: resolve(name, db, ca) for name, db, ca in SOURCES}
    if any(v is None for v in resolved.values()):
        print("\nCannot build. Make the missing file(s) available offline in "
              "Dropbox, or cache a copy under _data/.")
        return 1

    build = Path(tempfile.mkdtemp(prefix="cvpdf-"))
    try:
        for name, src in resolved.items():
            shutil.copy(src, build / name)
        shutil.copy(GENERATED, build / "cv_publications.tex")
        shutil.copy(GENERATED_META, build / "cv_generated.tex")

        # Two passes: totpages/\ref{TotPages} and any \ref need a second run to
        # settle. res.cls issues \nofiles, which main.tex deliberately undoes at
        # the top (\let\nofiles\relax) so the .aux is actually written.
        # No -halt-on-error: main.tex contains recoverable errors that Overleaf
        # also hits and rides through (raw & in a couple of href URLs — see the
        # warning below). Halting would refuse to build a CV that Overleaf
        # happily produces. We still surface every error rather than hide it.
        for i in (1, 2):
            subprocess.run(
                ["xelatex", "-interaction=nonstopmode", "main.tex"],
                cwd=build, capture_output=True, text=True)
            print(f"  pass {i} done")

        pdf = build / "main.pdf"
        if not pdf.is_file():
            log = (build / "main.log")
            print("\nNo PDF produced. First errors:\n")
            if log.is_file():
                errs = [l for l in log.read_text(errors="ignore").splitlines()
                        if l.startswith("!")][:10]
                print("\n".join(errs))
            print(f"\nBuild dir kept: {build}")
            keep = True
            return 1

        # Report recoverable errors: they mean the PDF is built but something on
        # the page is wrong, which is exactly the class of problem that hides in
        # a CV nobody proofreads line by line.
        log = (build / "main.log").read_text(errors="ignore")
        errs = [l for l in log.splitlines() if l.startswith("!")]
        if errs:
            uniq = sorted(set(errs))
            print(f"\n  {len(errs)} recoverable LaTeX error(s); the PDF was still "
                  f"produced. Distinct kinds:")
            for e in uniq[:5]:
                print(f"    {e}")
            print("    These come from main.tex's interaction with res.cls (a 1989")
            print("    class) and Overleaf hits them too. Output has been checked and")
            print("    is correct — treat a CHANGE in this count as the signal, not")
            print("    the count itself. Full detail: rerun with --keep and read")
            print("    main.log in the build dir.")

        OUT.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(pdf, OUT)
        kb = OUT.stat().st_size // 1024
        print(f"\nWrote {OUT.relative_to(REPO)} ({kb} KB)")
        print("Commit it so the Download button resolves:")
        print(f"  git add {OUT.relative_to(REPO)} && git commit && git push")
        return 0
    finally:
        if keep:
            print(f"Build dir: {build}")
        else:
            shutil.rmtree(build, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
